import Head from "next/head"
import Image from "next/image"
import Navbar from "../components/presentation/navbar"
import styles from "../styles/Home.module.css"
import { Article } from "../components/presentation/article"

export default function Home() {
  const tags = ["mecanica", "mantenimiento", "circuito", "tag4", "tag5"]

  return (
    <div className="bg-base-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <div
          class="hero min-h-screen"
          //style="background-image: url(https://api.lorem.space/image/fashion?w=1000&h=800);"
          style={{
            "background-image":
              "url(https://api.lorem.space/image/fashion?w=1000&h=800)",
          }}
        >
          <div class="hero-overlay bg-opacity-60"></div>
          <div class="hero-content text-center text-neutral-content">
            <div class="max-w-md">
              <h1 class="mb-5 text-7xl font-bold italic">
                PITBIKE<span className="font-thin">RS</span>
              </h1>
            </div>
          </div>
        </div>
      </main>
      <section className="max-w-5xl m-auto">
        <h2 className="text-6xl text-center font-bold my-6">Artículos</h2>
        <div className="my-24 grid grid-cols-1  gap-20  md:grid-cols-2  justify-items-center">
          <Article
            title={"titulo"}
            description={
              "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of  (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum"
            }
            data={"20/05/2021"}
            tags={tags}
            likes={12}
          />
          <Article
            title={"titulo"}
            description="probando"
            data={"20/05/2021"}
            tags={tags}
          />
          <Article
            title={"titulo"}
            description="probando"
            data={"20/05/2021"}
            tags={tags}
          />
          <Article
            title={"titulo"}
            description="probando"
            data={"20/05/2021"}
            tags={tags}
          />
          <Article
            title={"titulo"}
            description="probando"
            data={"20/05/2021"}
            tags={tags}
          />
        </div>
      </section>
    </div>
  )
}
