import Head from "next/head"
import Image from "next/image"
import Navbar from "../components/presentation/navbar"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className="bg-base-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <div
          class="hero min-h-screen"
          //style="background-image: url(https://api.lorem.space/image/fashion?w=1000&h=800);"
          style={{
            "background-image":
              "url(https://api.lorem.space/image/fashion?w=1000&h=800)",
          }}
        >
          <div class="hero-overlay bg-opacity-60"></div>
          <div class="hero-content text-center text-neutral-content">
            <div class="max-w-md">
              <h1 class="mb-5 text-7xl font-bold italic">
                PITBIKE<span className="font-thin">RS</span>
              </h1>
            </div>
          </div>
        </div>
      </main>
      <section>
        <h2 className="text-6xl text-center font-bold">Artículos</h2>
      </section>
    </div>
  )
}
